# unsqueeze

In [2]:
import torch

In [3]:
x = torch.tensor([2,3,5,7])

In [4]:
x

tensor([2, 3, 5, 7])

In [15]:
x.shape

torch.Size([4])

In [9]:
x.unsqueeze(0)

tensor([[2, 3, 5, 7]])

In [16]:
x.unsqueeze(0).shape

torch.Size([1, 4])

In [10]:
x.unsqueeze(1)

tensor([[2],
        [3],
        [5],
        [7]])

In [17]:
x.unsqueeze(1).shape

torch.Size([4, 1])